### ISSUE TITLE
PyLucene to be used?

### ISSUE THREAD

**Issue by muhac** [reinbugnot/tdm2023-project#1]
Hi Rein, I'm reading your code on indexing and searching. Do you plan to use libraries like [Lucene](https://lucene.apache.org/pylucene/), or implement future features by hand?

@reinbugnot @zyqdzkd

**Comment by reinbugnot** [comment]
Thanks for this Muhan! I tried writing a native search engine by hand for fun, hoping that showing we created a search engine with very fundamental tools will net us higher points. I got the basics down right so the search algorithm should work fine.

Whether or not to use this for our final output is up to us! We can try using IR libraries too and then make comparisons on our paper about the difference is performance and output. I think that would make our paper much stronger.
